config/routes.rb
Rails.application.routes.draw do
  resources :pins

  devise_for :users
  root 'pins#index'
  get 'home/about'
  
end

app/models/pin.rb
class Pin < ActiveRecord::Base
	belongs_to :user
	has_attached_file :image, :styles => { :large => "500x500>", :medium => "300x300>", :thumb => "100x100>"}
	validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :pins
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
  	devise_parameter_sanitizer.for(:sign_up) << :name
  	devise_parameter_sanitizer.for(:account_update) << :name
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index  	
  end

  def about
  end
end

app/controllers/pins_controller.rb
class PinsController < ApplicationController
  before_action :set_pin, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :correct_user, only: [:edit, :update, :destroy]

  
  def index
    @pins = Pin.all.order('created_at DESC')
  end

  def show
  end

  
  def new
    @pin = Pin.new
  end

  
  def edit
  end

 
  def create
    @pin = current_user.pins.build(pin_params)
    if @pin.save
      redirect_to @pin, notice: 'pin was successfully created'
    else
      render action: 'new'
    end
  end

  def update
    if @pin.update(pin_params)
      redirect_to @pin, notice: 'pin was successfully updated'
    else
      render action: 'edit'
    end
  end

 def destroy
    @pin.destroy
    redirect_to pins_url, notice: 'pin deleted'
 end

  private
   
    def set_pin
      @pin = Pin.find(params[:id])
    end

    def pin_params
      params.require(:pin).permit(:description, :image, :name)
    end

    def correct_user
      @pin = current_user.pins.find_by(id: params[:id])
      redirect_to pins_path, notice: 'not authorized to edit this pin' if @pin.nil?
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/pins_helper.rb
module PinsHelper
end

app/views/home/_header.html.erb
<nav class="navbar navbar-default" role="navigation">
	<div class="container">
		<div class="navbar-header">
			<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" >
				<span class="sr-only">Toggle navigation</span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</button>
			<%= link_to 'Pinterested app', root_path, class: 'navbar-brand' %>
		</div>

		<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
			<ul class="nav navbar-nav navbar-right">
				<li><%= link_to 'Home', root_path %></li>
				<li><%= link_to 'About us', home_about_path %></li>
				<li><%= link_to 'List pins', pins_path %></li>

				<% if user_signed_in? %>
				 	<li><%= link_to 'Add pin', new_pin_path %></li>
					<li><%= link_to 'Edit profile', edit_user_registration_path %></li>
					<li><%= link_to 'Logout', destroy_user_session_path, method: :delete %></li>
				<% else %>
					<li><%= link_to 'Login', new_user_session_path %></li>
					<li><%= link_to 'Join', new_user_registration_path %></li>
				<% end %>
			</ul>
		</div>
	</div>
</nav>


app/views/home/about.html.erb
<h1>About page</h1>

app/views/home/index.html.erb
<div class="jumbotron">
	<h1>Home#index</h1>
	<p>Find me in app/views/home/index.html.erb</p>
	<%= link_to 'About us', home_about_path, class: 'btn btn-default' %>
	<%= link_to 'Home', root_path, class: 'btn btn-primary' %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Pinterest</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width-device-width, initial-scale=1, maximum-scale=1">
</head>
<body>
	<%= render 'home/header' %>
	<div class="container">
		<% flash.each do |name, msg| %>
			<%= content_tag(:div, msg, class: 'alert alert-info') %>
		<% end %>
		<%= yield %>
	</div>
	

</body>
</html>

app/views/pins/_form.html.erb
<%= form_for @pin, html: { multipart: true }  do |f| %>
  <% if @pin.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@pin.errors.count, "error") %> prohibited this pin from being saved:</h2>

      <ul>
      <% @pin.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :description %><br>
    <%= f.text_field :description, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :image %>
    <%= f.file_field :image, class: 'form-control' %>
  </div>
  <div class="actions">
    <%= f.submit 'Create pin', class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/pins/edit.html.erb
<div class="panel panel-default">
	<div class="panel-heading">
		<h1>Editing Pin</h1>
	</div>
	<div class="panel-body">
		<%= render 'form' %>
	</div>
	<div class='panel-footer'>
		<%= link_to 'Show', @pin %> |
		<%= link_to 'Back', pins_path %>
	</div>
</div>

app/views/pins/index.html.erb
<div id="pins" class="transitions-enabled">
  <% @pins.each do |pin| %>
    <div class="box">
      <div class="panel panel-default">
      <%= link_to image_tag(pin.image.url(:medium)), pin %>
      <div class="panel-body">
        <%= pin.description %><br/>
        <strong><%= pin.user.name if pin.user %></strong>

      </div>

      <div class="panel-footer">
        <% if pin.user == current_user %>
          <%= link_to 'Edit', edit_pin_path(pin) %>
          <%= link_to 'Destroy', pin, method: :delete, data: { confirm: 'Are you sure?' } %>
        <% end %>
     </div>
     </div>
    </div>
  <% end %>  
</div>

app/views/pins/new.html.erb
<div class="panel panel-default">
	<div class="panel-heading">
		<h1>New Pin</h1>
	</div>
	<div class="panel-body">
		<%= render 'form' %>
	</div>
	<div class="panel-footer">
	  <%= link_to 'Back', pins_path %>
	</div>
</div>

app/views/pins/show.html.erb
<!-- <p id="notice"><%#= notice %></p> -->

<div class="row">
	<div class="col-md-offset-2 col-md-8">

		<div class="panel panel-default">
			<div class="panel-heading center">
				<%= image_tag @pin.image.url(:large), class: 'img-show' %>
			</div>
		    <div class="panel-body">
		    	 <%= @pin.description %><br/>
		    	 <%= @pin.user.name %><br>
		    	 <% if @pin.user == current_user %>
					<%= link_to 'Edit', edit_pin_path(@pin) %> 
				 <% end %>
				 <%= link_to 'Back', pins_path %>
		    </div>
		</div>
	</div>
</div>